<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/country.css">
    <title><?= $title ?></title>
  </head>
  <body>
    <header>
      <h1>🌏🌎🌍 Countries 'R Us!</h1>
    </header>
    <nav>
      <a href="countries.php">Countries Gallery</a>
      <a href="add.php">Add New Country</a>
    </nav>
    <main>    
      <h2><?= $title ?></h2>
