<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?></title>
  </head>
  <body>
  <body>
    <header>
      <h1>Week 7 Exercise <?= $exNum ?></h1>
    </header>
    <nav>
      <a href="ex01.php">Ex01</a>
      <a href="ex02.php">Ex02</a>
      <a href="ex03.php">Ex03</a>
      <a href="ex04.php">Ex04</a>
      <a href="ex05.php">Ex05</a>
      <a href="ex06.php">Ex06</a>
    </nav>    